### ISSUE TITLE
assigning current list to comment

### ISSUE THREAD

**Issue by banando** [banando/top5#1]
I'm currently working on this user story:
As a user i want to be able to comment on someone's list to show how i feel about that list

My create comment for a list doesn't work. when clicked it automatically directs me to the message show page but I'm trying to redirect back to the list page. Also i'm not sure how to save the current list to @comment.list. i got the @comment.user to work using @current_user, not sure where to go for current list.

```
class CommentsController < ApplicationController
  def new
    @comment = Comment.new

  end
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.list_id = 11
    if @comment.save
      flash[:notice] = "Comment added!"
      redirect_to '/lists/11'
    else
      render 'new'
    end

  end
  private
  def comment_params
    params.require(:comment).permit(:body, :user, :list)
  end

end
```

i've tried using the params.require(:list) to bring in the @list i need to set it into but i'm not really sure how that works. i was getting params empty errors
I was also tried manually setting it just to see if the comments would show up, as shown in the above code (setting it to 11), which worked. I'm just having issues with figuring out how to do it dynamically.

Errors:
I get a No data passed error from the browser not rails, when i refresh i get the No route error when it tries to take me to list/11/comment avoiding my redirect to list/11

**Comment by tambling** [comment]
In the future, please make sure your issues conform to the [guidelines](https://github.com/ga-students/WDI_DTLA_6/tree/master/projects/project_issues_protocol). Also, without code here, there isn't much we can do to help– either include a screenshot of the relevant code, or commit and push what you have and link to the relevant bits.

**Comment by banando** [comment]
My screenshot tool isn't working so i can't send snippets using that.

**Comment by banando** [comment]
I updates my issue to better reflect guidelines, please let me know if i'm still missing any info
