### ISSUE TITLE
Implementing likes without joint table ie.catinder

### ISSUE THREAD

**Issue by banando** [banando/top5#2]
I am working on the user story associated with being able to like a "list".
the errors i'm getting :
"ActionController::ParameterMissing in ListsController#update
param is missing or the value is empty: list

  private
  def list_params
    params.require(:list).permit!
  end
Rails.root: /Users/Chris/code/wdi/projects/top5"

I've tried messing with the parameters but i'm not quite sure what it's looking for in params. I think it might have something to do with my routes since update works when it's in a different route. But I'm really lost as to where to go from there. I am going to try and make the like available in the show instead of the index and see if that makes any difference. please help.

my code:

in list controller:

```
  def update
    list = List.find(params[:id])
    list.upvote! if params["vote"]
    if list.update(list_params)
      flash[:notice]= "Changes have been saved"
      redirect_to root_path
    else
      render 'edit'
    end

  end 
```

in list model

```
 class List < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  def upvote!
    self.update(likes: self.likes + 1)
  end

end

```

in my view  

```
<% if current_user == list.user %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Edit', edit_list_path(list) %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Delete', list, method: :delete, data: {confirm: 'Are you sure'} %>
            <% end %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Like', list_path(list, vote: true), method: :put %>
            (<%= list.likes %>)
```

**Comment by tambling** [comment]
So, when you use `params.require(:list)`, your controller is looking for `params["list"]`– check your server logs to make sure it's actually being passed in. If not, either require something that is being passed in, or just don't bother with strong params until you have a better idea of how your requests will be modeled.

**Comment by banando** [comment]
i got my likes to work, but now everything else started breaking
undefined method `name' for nil:NilClass
Extracted source (around line #77):
75
76
77
78
79
80

```
    <br>
    <%= time_ago_in_words c.created_at %> ago | by
    <%= c.user.name %> <br><br>
    <!-- display user -->

  </li>
```

**Comment by ghost** [comment]
@banando the object `c` does not have a `user` related to it.

Either give it a user to belong to, or check if there is a user it belongs to before calling `#name` on it.

**Comment by banando** [comment]
Thanks, somehow one of my comments didn't have a user associated with it.
